#!/bin/bash


usrEmail=""
echo "Enter your email address"
read usrEmail

git config user.email "$usrEmail"

cd Inbox

g++ main.cpp Inbox.cpp -o thisMessage

./thisMessage -m

rm thisMessage

cd ..

git add -A

cmtMsg=""
echo "Enter a commit message in quotes"
read cmtMsg

git commit -m "$cmtMsg"

git push -u origin message

cd ..

rm -rf Inbox
